version: '2'
services:
        web:
           build: nginx
           restart: always
           ports:
             - 80:80
           volumes:
             - ./logs/nginx:/var/log/nginx
             - ./nginx/configs:/etc/nginx/conf.d
             - ./projects:/var/www
           links:
             - fpm5.6
             - fpm7.0
             - fpm7.1
             - fpm7.2
        fpm5.6:
           build: php56
           ports:
             - 9004:9004
           volumes:
             - ./logs/php-fpm/php-fpm5_6.log:/var/log/php56_errors.log
             - ./projects:/var/www
        fpm7.0:
           build: php70
           ports:
             - 9001:9001
           volumes:
             - ./logs/php-fpm/php-fpm7_0.log:/var/log/php70_errors.log
             - ./projects:/var/www
        fpm7.1:
           build: php71
           ports:
             - 9002:9002
           volumes:
             - ./logs/php-fpm/php-fpm7_1.log:/var/log/php71_errors.log
             - ./projects:/var/www
        fpm7.2:
           build: php72
           ports:
             - 9003:9003
           volumes:
             - ./projects:/var/www
        redis:
           build: redis
           ports: 
             - 6379:6379
        db:
           image: mariadb:latest
           restart: always
           volumes:
             - ./db:/var/lib/mysql
           environment:
             MYSQL_ROOT_PASSWORD: root
             MYSQL_DATABASE: main
           ports:
             - 3306:3306
             - 9998:9998
             - 9999:9999
